import {
  AlertTriangle,
  Gift,
  Megaphone,
  Send,
  ShoppingBag,
  ShoppingCart,
  Star,
  Trophy,
} from 'lucide-react-native';

import { NotificationItem } from './types';

export const MOCK_NOTIFICATIONS: Record<string, NotificationItem[]> = {
  Hoje: [
    {
      id: '1',
      title: 'Você recebeu 250 moedas!',
      description: 'Troca de Item Premium foi concluída com sucesso.',
      time: 'Há 15 minutos',
      type: 'transaction',
      icon: ShoppingCart,
      iconBg: 'bg-green-700',
      read: false,
    },
    {
      id: '2',
      title: 'Bônus Diário Disponível',
      description: 'Resgate suas 100 moedas gratuitas agora!',
      time: 'Há 2 horas',
      type: 'offer',
      icon: Gift,
      iconBg: 'bg-blue-500',
      read: false,
    },
    {
      id: '3',
      title: 'Novos itens na loja!',
      description: 'Confira os lançamentos exclusivos de hoje.',
      time: 'Há 4 horas',
      type: 'offer',
      icon: ShoppingBag,
      iconBg: 'bg-purple-600',
      read: false,
    },
  ],
  Ontem: [
    {
      id: '4',
      title: 'Transferência enviada',
      description: 'Você enviou 50 moedas para Maria.',
      time: 'Ontem às 18:45',
      type: 'transaction',
      icon: Send,
      iconBg: 'bg-green-700',
      read: true,
    },
    {
      id: '5',
      title: 'Você subiu de nível!',
      description: 'Parabéns! Agora você é nível 15.',
      time: 'Ontem às 14:22',
      type: 'achievement',
      icon: Star,
      iconBg: 'bg-orange-500',
      read: true,
    },
    {
      id: '6',
      title: 'Ação necessária',
      description: 'Verifique seu e-mail para confirmar a alteração de senha.',
      time: 'Ontem às 09:12',
      type: 'alert',
      icon: AlertTriangle,
      iconBg: 'bg-red-500',
      read: true,
    },
  ],
  'Esta Semana': [
    {
      id: '7',
      title: 'Nova conquista desbloqueada!',
      description: 'Você completou 100 trocas bem-sucedidas.',
      time: '3 dias atrás',
      type: 'achievement',
      icon: Trophy,
      iconBg: 'bg-blue-500',
      read: true,
    },
    {
      id: '8',
      title: 'Promoção especial!',
      description: '30% de desconto em todos os itens premium até sexta-feira.',
      time: '5 dias atrás',
      type: 'offer',
      icon: Megaphone,
      iconBg: 'bg-purple-600',
      read: true,
    },
  ],
};
