export { default as BackIcon } from './Backicon.svg';
export { default as CheckIcon } from './Check.svg';
export { default as ErrorIcon } from './ErrorIcon.svg';
export { default as Eye } from './Eye.svg';
export { default as EyeOff } from './EyeOff.svg';
export { default as RedSentIcon } from './RedSentIcon.svg';
export { default as SuccessIconModal } from './SuccessIconModal.svg';
export { default as WarningIcon } from './WarningIcon.svg';
export { default as ClockIcon } from './ClockIcon.svg';
